export const GET_HISTORY_WEIGHT = "GET_HISTORY_WEIGHT";

export const GET_HISTORY_WEIGHT_START = "GET_HISTORY_WEIGHT_START";

export const GET_HISTORY_WEIGHT_SUCCESS = "GET_HISTORY_WEIGHT_SUCCESS";

export const GET_HISTORY_WEIGHT_ERROR = "GET_HISTORY_WEIGHT_ERROR";