export const GET_USER_REGISTER = "GET_USER_REGISTER";

export const GET_USER_REGISTER_START = "GET_USER_REGISTER_START";

export const GET_USER_REGISTER_SUCCESS = "GET_USER_REGISTER_SUCCESS";

export const GET_USER_REGISTER_ERROR = "GET_USER_REGISTER_ERROR";


export const GET_USER_CREDITS_START = "GET_USER_CREDITS_START";

export const GET_USER_CREDITS_SUCCESS = "GET_USER_CREDITS_SUCCESS";

export const GET_USER_CREDITS_ERROR = "GET_USER_CREDITS_ERROR";
