export const GET_USER_REGISTER = "GET_USER_REGISTER";

export const GET_MANAGEMENT_START = "GET_MANAGEMENT_START";

export const GET_MANAGEMENT_SUCCESS = "GET_MANAGEMENT_SUCCESS";

export const GET_MANAGEMENT_ERROR = "GET_MANAGEMENT_ERROR";
